import dev.s7a.gradle.minecraft.server.tasks.LaunchMinecraftServerTask
import dev.s7a.gradle.minecraft.server.tasks.LaunchMinecraftServerTask.JarUrl
import org.gradle.jvm.tasks.Jar

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("dev.s7a.gradle.minecraft.server") version "3.1.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.jetbrains:annotations:24.0.1")
    compileOnly("io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
}

group = "me.Scyphers.TokenPerms"
version = "1.6.0"
description = "TokenPerms"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

task<LaunchMinecraftServerTask>("testPlugin") {
    dependsOn("jar")
    doFirst {
        copy {
            from(tasks.getByName<Jar>("jar"))
            into(buildDir.resolve("MinecraftServer/plugins"))
        }
    }
    jarUrl.set(JarUrl.Paper("1.21"))
    agreeEula.set(true)
}