main: me.cyphers.fruitservers.tokenperms.Plugin
name: TokenPerms
version: 1.5.8
api-version: 1.16
author: Scyphers
depend:
  - Vault
commands:
  tokenperm:
    description: "For creating and monitoring token usage"
    aliases:
      - "tperm"